### ISSUE TITLE
error on DataFrame

### ISSUE THREAD

**Issue by Yerne** [WinVector/pyvtreat#2]
When tried to fit_transform on DataFrame got this:
```Traceback (most recent call last):

  File "<ipython-input-34-4749a25525c1>", line 2, in <module>
    train_labeled_vtreat.append(plan.fit_transform(pd.DataFrame(train_labeled[column]).all(), target))

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\__init__.py", line 297, in fit_transform
    raise Exception("X should be a Pandas DataFrame")

Exception: X should be a Pandas DataFrame
```
or this:

```
cross_frame = plan.fit_transform(train_labeled, target)
Traceback (most recent call last):

  File "<ipython-input-35-e8d2bce0ab6b>", line 1, in <module>
    cross_frame = plan.fit_transform(train_labeled, target)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\__init__.py", line 315, in fit_transform
    params=self.params_,

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\vtreat_impl.py", line 460, in fit_multinomial_outcome_treatment
    params=params,

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\vtreat_impl.py", line 176, in fit_binomial_impact_code
    sf = vtreat.util.grouped_by_x_statistics(x, y)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\util.py", line 31, in grouped_by_x_statistics
    if n != len(y):

TypeError: len() of unsized object
```

**Comment by JohnMount** [comment]
For `fit_transform()` the first argument is supposed to be a `pandas.DataFrame` and the second is supposed to be a vector-like object with a length equal to the number of rows the same as the `DataFrame` (and both should have trivial indexing).

In your first example `pd.DataFrame(train_labeled[column]).all()` is going to be a logical, not the required `DataFrame`.  Likely in your second example `target` is a value, not a column.  Assuming you are trying a classification problem, there is a worked example here: https://github.com/WinVector/pyvtreat/blob/master/Examples/Classification/Classification.ipynb

**Comment by Yerne** [comment]
All right, so i added Target column to first argument DataFrame, it is now gives 'Categorical' error

```
  File "<ipython-input-59-9df623fdbd02>", line 1, in <module>
    cross_frame = plan.fit_transform(train_labeled, train_labeled['target'])
....................
  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\arrays\categorical.py", line 2096, in __setitem__
    raise ValueError("Cannot setitem on a Categorical with a new "

ValueError: Cannot setitem on a Categorical with a new category, set the categories first
`

**Comment by Yerne** [comment]
ok, so it works, with smaller chunks of large dataset, maybe there is some limitations in size/RAM proportion or something.

**Comment by Yerne** [comment]
yes, something corrupted in dataset.

**Comment by JohnMount** [comment]
Ah, thanks for the notes.  I myself have been surprised that types can be mixed in Pandas data frames.  I am going to add some checks to get better error messages on that.

**Comment by Yerne** [comment]
So yea, my dataset has 'object' dtypes columns
<img src="https://aiaiai.tinytake.com/media/ab982c?filename=1565676614656_2_637012734118419018.png&sub_type=thumbnail_preview&type=attachment&width=752&height=418" title="Powered by TinyTake Screen Capture"/><br><a href="https://www.tinytake.com">Powered by TinyTake Screen Capture</a>

**Comment by Yerne** [comment]
I hope this information will help for development of this library.

**Comment by Yerne** [comment]
Here is trace of error, when i used this loop:
```
for column in train_labeled:
    dataframe = pd.DataFrame(train_labeled[column]).reset_index()
    dataframe['target'] = target.values
    train_labeled_vtreat.append(plan.fit_transform(dataframe.iloc[:,:(len(dataframe.columns)-1)], dataframe['target']))
```

it worked well untill it parced column of "category" dtype:
```
ValueError: Cannot setitem on a Categorical with a new category, set the categories first
```
<img src="https://aiaiai.tinytake.com/media/ab9c00?filename=1565684446345_2_637012812438240075.png&sub_type=thumbnail_preview&type=attachment&width=646&height=314" title="Powered by TinyTake Screen Capture"/><br><a href="https://www.tinytake.com">Powered by TinyTake Screen Capture</a>
so error on "category" dtype.

**Comment by Yerne** [comment]
So i changed categorical columns ->  ".astype(str)", and error is gone,
Sorry for mess, im not very well experienced in pandas myself.

**Comment by JohnMount** [comment]
No problem. I need to add support for categorical columns.

**Comment by JohnMount** [comment]
Yerne, I really appreciate you taking the time to try this and apologize for any rough edges you are encountering.  I am experimenting with more aggressive pre-processing of the DataFrame in the next version of vtreat (`.astype(str)` as part of the `vtreat` built in conversions).  If you are interested you can preview it with `pip install https://github.com/WinVector/pyvtreat/raw/master/pkg/dist/vtreat-0.2.3.tar.gz` (may need to `pip uninstall vtreat` first to get the new version to install).

**Comment by Yerne** [comment]
Yea, i will try it when ill got a spare moment.

**Comment by Yerne** [comment]
ok, im uninstalled old and installed new ver. and disabled this check

> 

    if train_labeled[column].values.dtype.name =="category":
        train_labeled[column]= train_labeled[column].astype(str)

it still gave error:

```
Traceback (most recent call last):

  File "<ipython-input-3-d03451cc70c1>", line 23, in <module>
    train_labeled_vtreat_t[col_t] = plan.transform(dataframe_t)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\__init__.py", line 207, in transform
    res = vtreat_impl.perform_transform(x=X, transform=self, params=self.params_)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\vtreat_impl.py", line 562, in perform_transform
    new_frames = [xfi.transform(x) for xfi in plan["xforms"]]

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\vtreat_impl.py", line 562, in <listcomp>
    new_frames = [xfi.transform(x) for xfi in plan["xforms"]]

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\vtreat\vtreat_impl.py", line 71, in transform
    sf.loc[na_posns, incoming_column_name] = "_NA_"

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\indexing.py", line 190, in __setitem__
    self._setitem_with_indexer(indexer, value)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\indexing.py", line 656, in _setitem_with_indexer
    value=value)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\internals\managers.py", line 510, in setitem
    return self.apply('setitem', **kwargs)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\internals\managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\internals\blocks.py", line 1752, in setitem
    self.values[indexer] = value

  File "C:\Users\TEMP.Main.001\.conda\envs\snakes\lib\site-packages\pandas\core\arrays\categorical.py", line 2096, in __setitem__
    raise ValueError("Cannot setitem on a Categorical with a new "

ValueError: Cannot setitem on a Categorical with a new category, set the categories first
```

**Comment by JohnMount** [comment]
The current Python `vtreat` isn't prepared to leave categorical columns as categorical (though that may make sense to add as a feature).  The line you disabled isn't so much a check as the code converting the categorical column to strings.  The error you see triggered laster is when `vtreat` then tries to replace a missing value with a new sentinel level `"_NA_"`.  In `vtreat` all result columns are numeric, so a string or categorical column is not going to be directly in the result frame anyway (unless it is one of the "columns to copy", which are copied- but not transformed).  The Python version of `vtreat` is a new package- but it is following some of the ideas and semantics of the original `R` version of the package: and the all transformed columns are numeric is a big part of the package intent.

**Comment by Yerne** [comment]
Thanks, your library and explanations are helpful to learn how to make machine learning pipelines,
